# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "mikrotik_api_url" {
  type = string
}

variable "mikrotik_username" {
  type      = string
  sensitive = true
}

variable "mikrotik_password" {
  type      = string
  sensitive = true
}
