# ==============================================================================
# Prod Shared Cluster - Input Variables
# ==============================================================================
# Provider credentials are generated by provider.hcl (provider_variables.tf).
variable "cluster_name" {
  type = string
}

variable "cluster_endpoint" {
  type = string
}

variable "talos_version" {
  type = string
}

variable "kubernetes_version" {
  type = string
}

variable "network_bridge" {
  type = string
}

variable "network_gateway" {
  type = string
}

variable "dns_servers" {
  type = list(string)
}

variable "vip_ip" {
  type = string
}

variable "datastore_id" {
  type = string
}

variable "talos_image_id" {
  description = "Proxmox file ID for the Talos disk image"
  type        = string
}

variable "control_plane_nodes" {
  type = map(object({
    node_name    = string
    vm_id        = number
    hostname     = string
    ip_address   = string
    cpu_cores    = number
    memory_mb    = number
    disk_size_gb = number
  }))
}

variable "worker_nodes" {
  type = map(object({
    node_name           = string
    vm_id               = number
    hostname            = string
    ip_address          = string
    cpu_cores           = number
    memory_mb           = number
    disk_size_gb        = number
    gpu_passthrough     = bool
    gpu_mapping_id      = optional(string, "")
    hook_script_file_id = optional(string, "")
  }))
}

variable "talos_schematic_id" {
  description = "Talos Factory schematic ID"
  type        = string
}

variable "tags" {
  type = list(string)
}

variable "deploy_bootstrap" {
  type = bool
}

variable "truenas_api_url" {
  type    = string
  default = ""
}

variable "truenas_api_key" {
  type      = string
  sensitive = true
  default   = ""
}

variable "truenas_nfs_dataset" {
  type    = string
  default = ""
}

variable "truenas_iscsi_portal" {
  type    = string
  default = ""
}

variable "truenas_iscsi_dataset" {
  type    = string
  default = ""
}

variable "truenas_nfs_fast_dataset" {
  type    = string
  default = ""
}

variable "truenas_nfs_scratch_dataset" {
  type    = string
  default = ""
}

variable "metallb_ip_range" {
  type    = string
  default = ""
}

variable "traefik_enabled" {
  type    = bool
  default = false
}

variable "tailscale_enabled" {
  type    = bool
  default = false
}

variable "tailscale_oauth_client_id" {
  type      = string
  sensitive = true
  default   = ""
}

variable "tailscale_oauth_client_secret" {
  type      = string
  sensitive = true
  default   = ""
}

variable "tailscale_hostname" {
  type    = string
  default = "traefik"
}

variable "traefik_acme_enabled" {
  type    = bool
  default = false
}

variable "traefik_acme_email" {
  type    = string
  default = ""
}

variable "traefik_acme_server" {
  type    = string
  default = "https://acme-staging-v02.api.letsencrypt.org/directory"
}

variable "cloudns_auth_id" {
  type      = string
  sensitive = true
  default   = ""
}

variable "cloudns_auth_password" {
  type      = string
  sensitive = true
  default   = ""
}
