---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arr-stack
  namespace: arr-stack
spec:
  interval: 10m
  releaseName: arr-stack
  chart:
    spec:
      chart: ./charts/arr-stack
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: arr-stack-values
  upgrade:
    remediation:
      retries: 0
