# ==============================================================================
# Jellyfin Media Server - Input Variables
# ==============================================================================
# Provider credentials are generated by provider.hcl (provider_variables.tf).
variable "node_name" {
  type = string
}

variable "vm_id" {
  type = number
}

variable "vm_name" {
  type = string
}

variable "vm_description" {
  type    = string
  default = ""
}

variable "tags" {
  type    = list(string)
  default = []
}

variable "cpu_cores" {
  type    = number
  default = 8
}

variable "memory_mb" {
  type    = number
  default = 8192
}

variable "boot_disk_size_gb" {
  type    = number
  default = 32
}

variable "network_bridge" {
  type    = string
  default = "vmbr20"
}

variable "enable_dual_network" {
  type    = bool
  default = false
}

variable "secondary_bridge" {
  type    = string
  default = "vmbr10"
}

variable "pool_id" {
  type    = string
  default = null
}

variable "iso_id" {
  type    = string
  default = null
}

# Display
variable "vga_type" {
  type    = string
  default = "virtio"
}

variable "enable_serial_console" {
  type    = bool
  default = false
}

# PCI Passthrough
variable "enable_pci_passthrough" {
  type    = bool
  default = false
}

variable "pci_mapping_id" {
  type    = string
  default = null
}

# Cloud-init
variable "enable_cloud_init" {
  type    = bool
  default = false
}

variable "ip_address" {
  type    = string
  default = null
}

variable "gateway" {
  type    = string
  default = null
}

variable "nameserver" {
  type    = string
  default = null
}

variable "username" {
  type    = string
  default = null
}
