PROXMOX_TOKEN_ID=op://Homelab/Proxmox API Token/token_id
PROXMOX_TOKEN_SECRET=op://Homelab/Proxmox API Token/token_secret
MIKROTIK_USERNAME=op://Homelab/MikroTik Terraform API/username
MIKROTIK_PASSWORD=op://Homelab/MikroTik Terraform API/credential
B2_KEY_ID=op://Homelab/Backblaze B2/key_id
B2_APPLICATION_KEY=op://Homelab/Backblaze B2/application_key
TF_VAR_openvpn_user=op://Homelab/OpenVPN/username
TF_VAR_openvpn_password=op://Homelab/OpenVPN/password
TF_VAR_soulseek_username=op://Homelab/Soulseek/username
TF_VAR_soulseek_password=op://Homelab/Soulseek/password
TRUENAS_SMB_PASSWORD=op://Homelab/TrueNAS SMB User/password
TF_VAR_argocd_admin_password=op://Homelab/ArgoCD Admin/password
TF_VAR_truenas_api_key=op://Homelab/TrueNAS API Key/credential
TF_VAR_tailscale_api_key=op://Homelab/Tailscale API Key/credential
TF_VAR_tailscale_tailnet=op://Homelab/Tailscale API Key/tailnet
TF_VAR_cloudns_auth_id=op://Homelab/ClouDNS API/auth_id
TF_VAR_cloudns_auth_password=op://Homelab/ClouDNS API/password
TF_VAR_acme_email=op://Homelab/ACME Email/email
ARGOCD_API_TOKEN=op://Homelab/ArgoCD API Token/credential
SIGNOZ_API_KEY=op://Homelab/SigNoz API Key/credential
