# Provider credentials are generated by provider.hcl (provider_variables.tf).

variable "talos_version" {
  description = "Talos Linux version"
  type        = string
}

variable "schematic_id" {
  description = "Talos Image Factory schematic ID"
  type        = string
}

variable "proxmox_node" {
  description = "Proxmox node name"
  type        = string
}

variable "datastore_id" {
  description = "Datastore for image storage"
  type        = string
}
