---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  {{- if or .Values.server.gpu.enabled .Values.machineLearning.gpu.enabled }}
  labels:
    pod-security.kubernetes.io/enforce: privileged
  {{- end }}
  annotations:
    {{- include "immich.annotations" . | nindent 4 }}
