---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickstack-basicauth
  namespace: clickstack
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: clickstack-basicauth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: clickstack-basicauth
