---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: clickstack-credentials
  namespace: clickstack
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: clickstack-credentials
    creationPolicy: Owner
  data:
    - secretKey: appUserPassword
      remoteRef:
        key: clickstack/appUserPassword
    - secretKey: otelUserPassword
      remoteRef:
        key: clickstack/otelUserPassword
    - secretKey: apiKey
      remoteRef:
        key: clickstack/apiKey
