# ==============================================================================
# Dev Test Cluster - Input Variables
# ==============================================================================
# Provider credentials are generated by provider.hcl (provider_variables.tf).
variable "cluster_name" {
  type = string
}

variable "cluster_endpoint" {
  type = string
}

variable "talos_version" {
  type = string
}

variable "kubernetes_version" {
  type = string
}

variable "network_bridge" {
  type = string
}

variable "network_gateway" {
  type = string
}

variable "dns_servers" {
  type = list(string)
}

variable "vip_ip" {
  type = string
}

variable "datastore_id" {
  type = string
}

variable "talos_image_id" {
  description = "Proxmox file ID for the Talos disk image"
  type        = string
}

variable "control_plane_nodes" {
  type = map(object({
    node_name    = string
    vm_id        = number
    hostname     = string
    ip_address   = string
    cpu_cores    = number
    memory_mb    = number
    disk_size_gb = number
  }))
}

variable "worker_nodes" {
  type = map(object({
    node_name       = string
    vm_id           = number
    hostname        = string
    ip_address      = string
    cpu_cores       = number
    memory_mb       = number
    disk_size_gb    = number
    gpu_passthrough = bool
  }))
}

variable "tags" {
  type = list(string)
}

variable "deploy_bootstrap" {
  type = bool
}
