---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: osxphotos-export
resources:
  - helmrelease.yaml
configMapGenerator:
  - name: osxphotos-export-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
