---
datasets:
  # Bulk pool
  bulk_kubernetes_nfs_dynamic:
    recordsize: "128K"
    compression: "lz4"
    sync: "standard"
    quota: "10T"

  bulk_media:
    recordsize: "1M"
    compression: "lz4"
    sync: "standard"
    atime: "off"
    acltype: "nfsv4"
    aclmode: "passthrough"
    children:
      - books
      - movies
      - music
      - tv

  bulk_photos:
    recordsize: "1M"
    compression: "lz4"
    sync: "standard"
    atime: "off"
    acltype: "nfsv4"
    aclmode: "passthrough"

  bulk_backups_timemachine:
    recordsize: "1M"
    compression: "zstd"
    sync: "standard"
    quota: "2T"
    casesensitivity: "insensitive"
    acltype: "nfsv4"
    aclmode: "restricted"

  bulk_backups_proxmox:
    recordsize: "1M"
    compression: "zstd"
    sync: "standard"

  bulk_backups_restic_repo:
    recordsize: "128K"
    compression: "off" # Restic handles own compression
    sync: "standard"

  bulk_backups_forgejo:
    recordsize: "128K"
    compression: "zstd"
    sync: "standard"
    quota: "100G"

  bulk_archive:
    recordsize: "1M"
    compression: "lz4"
    sync: "standard"
    acltype: "nfsv4"
    aclmode: "passthrough"

  bulk_downloads:
    recordsize: "128K"
    compression: "off"
    sync: "disabled"
    children:
      - incomplete
      - complete
    acltype: "nfsv4"
    aclmode: "passthrough"

  bulk_aurral_downloads:
    recordsize: "128K"
    compression: "lz4"
    sync: "disabled"

  bulk_registry_cache:
    recordsize: "128K"
    compression: "lz4"
    sync: "standard"

  # Fast pool
  fast_kubernetes_nfs_dynamic:
    recordsize: "16K"
    compression: "lz4"
    sync: "standard"
    quota: "4T"

  fast_kubernetes_nfs_static:
    recordsize: "128K"
    compression: "lz4"
    sync: "standard"

  fast_kubernetes_iscsi_zvols:
    type: "filesystem" # Parent is filesystem, children are zvols
    compression: "lz4"

  fast_vms:
    recordsize: "64K"
    compression: "lz4"
    sync: "standard"

  fast_ml_models:
    recordsize: "1M"
    compression: "lz4"
    sync: "standard"
    quota: "1T"

  fast_dump:
    recordsize: "128K"
    compression: "lz4"
    sync: "standard"
    acltype: "nfsv4"
    aclmode: "passthrough"
