---
snapshot_policies:
  bulk_media:
    hourly: 0
    daily: 7
    weekly: 4
    monthly: 3
    replicate: false

  bulk_photos:
    hourly: 0
    daily: 30
    weekly: 8
    monthly: 12
    replicate: true

  bulk_container_registry:
    hourly: 0
    daily: 7
    weekly: 0
    monthly: 0
    replicate: false

  bulk_backups:
    daily: 7
    weekly: 4
    monthly: 6
    replicate: false

  ssd_kubernetes:
    hourly: 24
    daily: 7
    weekly: 4
    monthly: 6
    replicate: true
