---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aurral
  namespace: aurral
spec:
  interval: 10m
  releaseName: aurral
  chart:
    spec:
      chart: ./charts/aurral
      sourceRef:
        kind: GitRepository
        name: flux-system
        namespace: flux-system
      interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: aurral-values
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
      strategy: rollback
