---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prom-remotewrite-basicauth
  namespace: monitoring
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: prom-remotewrite-basicauth
    creationPolicy: Owner
  data:
    - secretKey: users
      remoteRef:
        key: Prometheus Remote Write/users
