---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-telegram
  namespace: monitoring
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: alertmanager-telegram
    creationPolicy: Owner
  data:
    - secretKey: BOT_TOKEN
      remoteRef:
        key: alertmanager-telegram/BOT_TOKEN
    - secretKey: CHAT_ID
      remoteRef:
        key: alertmanager-telegram/CHAT_ID
