---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - prometheusrule-wan.yaml
  - ingress-grafana.yaml
  - external-secret-remotewrite.yaml
  - middleware-basicauth.yaml
  - ingress-remotewrite.yaml
  - external-secret-grafana.yaml
  - external-secret-telegram.yaml
configMapGenerator:
  - name: kube-prometheus-stack-values
    files:
      - values.yaml
    options:
      disableNameSuffixHash: true
  - name: grafana-dashboard-wan-health
    files:
      - dashboards/wan-health.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
  - name: grafana-dashboard-photo-pipeline
    files:
      - dashboards/photo-pipeline.json
    options:
      disableNameSuffixHash: true
      labels:
        grafana_dashboard: "1"
