# ==============================================================================
# Resource Pools - Input Variables
# ==============================================================================
# Provider credentials are generated by provider.hcl (provider_variables.tf).

variable "pools" {
  type = map(object({
    id      = string
    comment = string
  }))
  description = "Map of resource pools to create"
}
