# ==============================================================================
# Images - Input Variables
# ==============================================================================
# Provider credentials are generated by provider.hcl (provider_variables.tf).
variable "truenas_url" {
  type        = string
  description = "TrueNAS ISO download URL"
}

variable "truenas_filename" {
  type        = string
  description = "TrueNAS ISO filename"
}

# NixOS ISO
variable "nixos_url" {
  type        = string
  description = "NixOS ISO download URL"
}

variable "nixos_filename" {
  type        = string
  description = "NixOS ISO filename"
}

variable "truenas_checksum" {
  type        = string
  description = "SHA256 checksum for TrueNAS ISO"
  default     = ""
}

variable "nixos_checksum" {
  type        = string
  description = "SHA256 checksum for NixOS ISO"
  default     = ""
}

variable "proxmox_node_primary" {
  type        = string
  description = "Primary Proxmox node name"
}

variable "proxmox_node_secondary" {
  type        = string
  description = "Secondary Proxmox node name"
}

variable "datastore_id" {
  type        = string
  description = "Datastore for ISO storage"
}

variable "talos_version" {
  type        = string
  description = "Talos Linux version"
}

variable "talos_schematic_id" {
  type        = string
  description = "Talos Image Factory schematic ID"
}
