---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: n8n
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  sources:
    - repoURL: 8gears.container-registry.com/library
      chart: n8n
      targetRevision: "2.0.1"
      helm:
        valueFiles:
          - $values/kubernetes/apps/n8n/overlays/shared/values.yaml
    - repoURL: https://github.com/svnlto/homelab
      targetRevision: HEAD
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: n8n

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
