---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otel-hyperdx-apikey
  namespace: otel-collector
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: otel-hyperdx-apikey
    creationPolicy: Owner
  data:
    - secretKey: HYPERDX_API_KEY
      remoteRef:
        key: clickstack/ingestionKey
