---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: otel-collector-ingest
  namespace: clickstack
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: otel-collector-ingest
    creationPolicy: Owner
  data:
    - secretKey: ingestionKey
      remoteRef:
        key: clickstack/ingestionKey
