---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: otel-cluster
  namespace: otel-collector
spec:
  interval: 30m
  releaseName: otel-cluster
  chart:
    spec:
      chart: opentelemetry-collector
      sourceRef:
        kind: HelmRepository
        name: opentelemetry
      interval: 1h
  valuesFrom:
    - kind: ConfigMap
      name: otel-cluster-values
