---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: otel-collector
resources:
  - namespace.yaml
  - helmrepository.yaml
  - external-secret.yaml
  - helmrelease-daemonset.yaml
  - helmrelease-deployment.yaml
configMapGenerator:
  - name: otel-agent-values
    files:
      - values.yaml=values-daemonset.yaml
    options:
      disableNameSuffixHash: true
  - name: otel-cluster-values
    files:
      - values.yaml=values-deployment.yaml
    options:
      disableNameSuffixHash: true
