# Provider credentials are generated by provider.hcl (provider_variables.tf).

variable "bridge_name" {
  type = string
}

variable "vlans" {
  type = map(object({
    id          = number
    name        = string
    subnet      = string
    gateway     = string
    description = string
  }))
}

variable "access_ports" {
  type = map(object({
    interface = string
    pvid      = number
    comment   = string
  }))
}

variable "trunk_ports" {
  type = map(object({
    interface = string
    comment   = string
  }))
}

variable "storage_l2mtu" {
  type        = number
  description = "L2MTU for SFP+ trunk ports (max frame size, requires reboot)"
  default     = 10218
}

variable "storage_mtu" {
  type        = number
  description = "MTU for SFP+ trunk ports (jumbo frames for storage VLAN)"
  default     = 9000
}

variable "wan_interface" {
  type        = string
  description = "WAN interface name (standalone, not in bridge)"
}

variable "wan_address" {
  type        = string
  description = "WAN IP address with CIDR (e.g. 192.168.8.2/24)"
}

variable "wan_gateway" {
  type        = string
  description = "WAN default gateway IP"
}

variable "allowed_management_subnets" {
  type        = string
  description = "Comma-separated subnets allowed to access management services"
}
