# Provider credentials are generated by provider.hcl (provider_variables.tf).

variable "vlan_interfaces" {
  type = map(string)
}

variable "wan_interface" {
  type = string
}

variable "pihole_ip" {
  description = "Pi-hole IP address for DNS firewall rules"
  type        = string
}
